name: Deploy Hugo site to GitHub Pages

# 触发条件，push 到 main 分支时触发
on:
  push:
    branches:
      - main  # 或者你的 Hugo 项目的主要分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Hugo 环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # 使用最新的 Hugo 版本

      # 构建 Hugo 站点
      - name: Build site
        run: hugo --minify

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public